version: 2 # Required: specifies the Dependabot configuration version (v2 is the latest).

updates:
  # Configuration for updating Go module dependencies.
  - package-ecosystem: gomod # Specifies the package ecosystem (Go modules).
    directory: / # Directory where the dependency files are located (root directory).
    schedule:
      interval: weekly # Check for updates weekly.
      day: monday # Run the update check every Monday.

  # Configuration for updating GitHub Actions dependencies.
  - package-ecosystem: github-actions # Specifies the package ecosystem (GitHub Actions).
    directory: / # Directory where the dependency files are located (root directory).
    schedule:
      interval: weekly # Check for updates weekly.
      day: monday # Run the update check every Monday.
